package cloud.autotests.tests;

import cloud.autotests.helpers.DriverUtils;
import com.codeborne.selenide.Condition;
import io.qameta.allure.Description;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.openqa.selenium.By;

import static com.codeborne.selenide.Condition.text;
import static com.codeborne.selenide.Selectors.*;
import static com.codeborne.selenide.Selenide.*;
import static io.qameta.allure.Allure.step;
import static org.assertj.core.api.Assertions.assertThat;



public class GeneratedTests extends TestBase {
    static final String BASE_URL = "https://gost-group.ru/en/";

    @Test
    @Description("Autogenerated test")
    @DisplayName("Тест содержание главной страницы")
    void titleTest() {
        step("Открытие ссылки  'https://gost-group.ru/en/'", () ->
            open("https://gost-group.ru/en/"));

        step("Заголовок страницы содержит следующий текст 'Process automation. Expert solution for system " +
                "integration'", () -> {
            String expectedTitle = "Process automation. Expert solution for system integration";
            String actualTitle = title();

            assertThat(actualTitle).isEqualTo(expectedTitle);
        });
    }

    @Test
    @DisplayName("Тест выбор русской версии сайта")
    void testMobile() {
        step("Открытие ссылки 'https://gost-group.ru/en/'", () -> {
                open(BASE_URL);
            $(byId("lang_choice_1")).selectOptionByValue("ru");
        });

            step("Проверка изменения версии", () -> {
                String expectedTitle = "Автоматизация Бизнес-процессов, Экспертные решения";
                String actualTitle = title();

                assertThat(actualTitle).isEqualTo(expectedTitle);
            });
    }

    @Test
    @DisplayName("Тест контактной инфомации об организации : адрес")
    void testAdress() {
        step("Open url 'https://gost-group.ru/about/'", () -> {
            open(BASE_URL+ "about/");
            $(".contacts-page-address").shouldHave(Condition.text("107140, г. Москва, ул. Русаковская, д" +
                    ".13, стр.5"));
        });
    }

    @Test
    @Description("Autogenerated test")
    @DisplayName("Page console log should not have errors")
    void consoleShouldNotHaveErrorsTest() {
        step("Open url 'https://gost-group.ru/en/'", () ->
                open(BASE_URL));

        step("Console logs should not contain text 'SEVERE'", () -> {
            String consoleLogs = DriverUtils.getConsoleLogs();
            String errorText = "SEVERE";

            assertThat(consoleLogs).doesNotContain(errorText);
        });
    }
}